### ISSUE TITLE
Read about the resort

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/golfers-dream#1]
EPIC: Read about the resort

USER STORY: As a **Site User** I can **view images and read about the resort** so that **I can decide if it is for me**

### Acceptance Criteria:

- [x] Images are present
- [x] The images are accompanied by a small amount of text

### Tasks

- [x] Task 1: Choose appropriate images.
- [x] Task 2: Implement images on the page.
- [x] Task 3: Write accompanying text to each image.
