### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/golfers-dream#10]
EPIC: Easy to navigate home page

USER STORY: As a **user** I can **easily navigate from the home page since it is not cluttered** so that **I can get to what I want fast.**

### Acceptance Criteria:

- [x] The home page has a striking hero image.
- [x] On top of the image is a text box with some text and a button.
- [x] The button leads to the booking page.
- [x] In case they are not signed in the booking page has additional buttons leading them where they need to go.

### Tasks

- [x] implement a large striking image on the home page.
- [x] Place a semi transparent box on top of the image.
- [x] Write som text inside the box.
- [x] Place a button under the text, inside the box, that leads to the booking page.
- [x] Make sure buttons on the booking page leads the user on if they are nog signed in.
