### ISSUE TITLE
Register account

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/golfers-dream#2]
EPIC: Users can sign up for an account

USER STORY: As a **Site User** I can **create an account** so that **I can sign in.**

### Acceptance Criteria:

- [x] User can create an account
- [x] Then they can sign in

### Tasks

- [x] Task 1: Install allauth.
- [x] Task 2: Customize the sign in, sign out and sign up pages.
