### ISSUE TITLE
View bookings

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/golfers-dream#3]
Epic: Users can see their bookings

USER STORY: As a **Site User** I can **go to my profile page** so that **I can see my bookings**

### Acceptance Criteria:

- [x] When a user is signed in they can see the bookings they have made.
- [x] If no bookings are made, display a message with a redirect button to the booking page.

### Tasks

- [x] Create a view for the profile page to display their bookings.
- [x] Create a template that display their bookings.
- [x] In the template, display a message with a redirect to the booking page, if they have no bookings.
