### ISSUE TITLE
Edit and Delete booking

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/golfers-dream#4]
EPIC: Users can edit and delete their bookings

USER STORY: As a **Site User** I can **edit and delete my bookings** so that **I can adjust my bookings if I change my mind**

### Acceptance Criteria:

- [x] When a user is signed in they can edit their bookings.
- [x] They can also delete their bookings.
- [x] When deleting their booking there is a confirmation page.

### Tasks
- [x] Create a view for edit booking.
- [x] Create a template for edit booking.
- [x] Create a view for delete booking.
- [x] Create a template for delete booking.
