### ISSUE TITLE
View incoming contact requests

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/golfers-dream#6]
EPIC: Users can contact the resort

USER STORY: As a **Site Admin** I can **view contact requests from the contact form** so that **I can respond to the request**

### Acceptance Criteria:

- [x] The model should contain name, email, message, marks as read and created on.
- [x] When a user has sent the form from the contact page.
- [x] I can view the form they sent.
- [x] I can mark it as read.

### Tasks

- [x] Task 1: Design the model.
- [x] Task 2: Register the model in admin panel.
- [x] Task 3: Design the form with fields in this order: name, email, massage.
- [x] Task 4: Implement the form on the contact page.
- [x] Task 5: Write tests for the form to make sure it functions as intended.
