### ISSUE TITLE
Make a booking

### ISSUE THREAD

**Issue by hogbergmarkus** [hogbergmarkus/golfers-dream#8]
EPIC: Create bookings

USER STORY: As a **Site User** I can **make a booking with the resort** so that **I have a reservation.**

### Acceptance Criteria:

- [x] Given a signed in user they can make a booking.

### Tasks:

- [x] Create Booking model with the fields: customer, first name, last name, email, check in, check out, number of people, message, created on, status (with the choices of pending, approved and denied).
- [x] Register the model in the admin panel with relevant information.
- [x] Create a form for the booking model.
- [x] Create view for booking.
- [x] Create template for booking.
- [x] Write tests for the form to make sure it handles user error.
